- .travis.yml
- appveyor.yml
@GuillaumeGomez also please set the "rolling builds" flag in appveyor settings.
> Making CI work

- README.md
> Fix appveyor badge

- src/lib.rs
- src/resources.rs
Close https://github.com/gtk-rs/glib/issues/120
> Add resources_[un]register

- Gir.toml
- src/auto/functions.rs
Fix gtk-rs/gtk#517
I'am not good with gir and copy this from glib crate, so hope this is ok.
> Link error gio on windows fix

- Cargo.toml
- README.md
> Lgpl update

- Gir.toml
- src/auto/notification.rs
Part of https://github.com/gtk-rs/gir/issues/403
> Add version for Notification::set_priority

- .travis.yml
- src/socket.rs
Fix doc builds found in https://github.com/gtk-rs/gtk/pull/622
cc @GuillaumeGomez , @sdroege
> Fix doc build

- src/unix_socket_address.rs
Fix error found on building docs in https://github.com/gtk-rs/gdk/pull/194
> Fix build docs for non unix

- src/gio_future.rs
See https://github.com/gtk-rs/glib/pull/333
> Update for MainContext::ref_thread_default() API changes

- src/subprocess_launcher.rs
> Fix doc build on windows

- src/lib.rs
- src/prelude.rs
> Clean up prelude a bit

- build.rs
Follow-up #152
сс @GuillaumeGomez
> Fix LGPL-doc test

- Gir.toml
- src/auto/volume_monitor.rs
Fixes https://github.com/gtk-rs/gio/issues/158
> VolumeMonitor::get() can never return None

- Gir.toml
- src/prelude.rs
Part of https://github.com/gtk-rs/gir/issues/683
WIP as I added parent manual traits only up to file_input_stream.rs and trying teach gir do it.
> Define manual traits

- src/test_util.rs
> Fix failing test compilation

- Gir.toml
- src/auto/file.rs
- src/auto/socket_listener.rs
- src/socket_listener.rs
See https://github.com/gtk-rs/gio/issues/99 and https://github.com/gtk-rs/gio/issues/161
> Two Option-related fixes

- Cargo.toml
- src/subclass/application.rs
Part of gtk-rs/gir#820.
cc @EPashkin @sdroege
> Improve docs.rs documentation

- Gir.toml
- src/auto/app_info.rs
Part of https://github.com/gtk-rs/gir/issues/829 and https://github.com/gtk-rs/gio/issues/236
cc @GuillaumeGomez, @sdroege
> Ignore AppInfo::launch_uris_async

- .travis.yml
- Cargo.toml
- src/file.rs
- src/input_stream.rs
- src/lib.rs
- src/output_stream.rs
- src/pollable_input_stream.rs
- src/socket.rs
- src/socket_listener.rs
- src/subprocess.rs
Part of gtk-rs/gtk#887
The second commit is for a better dox support.
cc @sdroege @EPashkin
> Remove subclass feature

- Gir.toml
- src/auto/unix_mount_point.rs
Fixes https://github.com/gtk-rs/gio/issues/245
CC @GuillaumeGomez @EPashkin
> Change UnixMountPoint getters to not require &mut self

- Gir.toml
- src/auto/desktop_app_info.rs
- src/desktop_app_info.rs
- src/prelude.rs
Reopening of #230 
cc @sdroege @EPashkin
> More types

- Cargo.toml
- src/input_stream.rs
- src/lib.rs
- src/output_stream.rs
- src/pollable_input_stream.rs
- src/pollable_output_stream.rs
> Some updates to the I/O streams

- src/subclass/seekable.rs
> Remove usage of glib_floating_reference_guard!()

- src/prelude.rs
Part of https://github.com/gtk-rs/examples/pull/283
cc @GuillaumeGomez, @sdroege
> Fix version in prelude

- .travis.yml
- Gir.toml
> Add manual trait doc check

- Gir.toml
- src/auto/threaded_socket_service.rs
- src/lib.rs
- src/threaded_socket_service.rs
It'll have a conflict with #301 but I'll update once #301 is merged.
cc @sdroege @EPashkin
> Improve ThreadedSocketService::new

- Gir.toml
- src/auto/drive.rs
- src/auto/mount.rs
- src/auto/volume.rs
Based on https://developer.gnome.org/gio/stable/GMount.html
> Make some returns non-nullable

- src/read_input_stream.rs
- src/subclass/application.rs
- src/subclass/input_stream.rs
- src/subclass/io_stream.rs
- src/subclass/output_stream.rs
- src/subclass/seekable.rs
- src/write_output_stream.rs
> Update for removal of ObjectImpl::get_type_data()
