gtk-rs/gio

Gir.toml, src/auto/socket.rs, src/socket.rs
We need to provide a callback, etc. for this function to be useful.
=> Fix-up Socket::create_source() implementation

src/lib.rs
Part of https://github.com/gtk-rs/gio/pull/80
cc @GuillaumeGomez
=> Make stub traits under feature="dox" public to include in doc

Gir.toml, src/auto/cancellable.rs, src/auto/mod.rs
=> Make Cancellable Send+Sync and don't generate trait for it

Gir.toml, src/auto/cancellable.rs, src/auto/mod.rs
commit c48c9a8c7a577244a051b0a580fb4681a0435c59 (HEAD -> cancellable-no-reset)
Author: Sebastian Dröge <sebastian@centricular.com>
Date:   Mon Apr 9 18:19:26 2018 +0200
Remove Cancellable::reset()
It can easily cause undefined behaviour, see
https://github.com/gtk-rs/gio/pull/102#issuecomment-379690071
=> Remove Cancellable::reset()

src/test_util.rs
* Create separate context for each invocation instead of using global one.
* Configure thread default context before invoking closure so that
operations will be executed in correct context.
* Avoid creating additional threads, they are unnecessary.
Fixes issue #93
=> Avoid main context interference when running async tests.

Gir.toml, src/auto/file.rs, src/file.rs, src/lib.rs
The contents need to be owned until the callback has triggered.
=> Implement File::replace_contents_async manually

src/unix_socket_address.rs
Fix error found on building docs in gtk-rs/gdk#194
=> Fix build docs for non unix (second attempt)

src/unix_socket_address.rs
And never pass NULL to slice::from_raw_part(), it's undefined behaviour
=> Use a const pointer for the slice returned from g_unix_socket_address_get_path()

Gir.toml, src/auto/output_stream.rs, src/input_stream.rs, src/output_stream.rs
It can return an error *and* can have bytes written out. We have to
return the written bytes in any case, and did so already for the async
variants and InputStream::read_all().
Fixes https://github.com/gtk-rs/gio/issues/149
=> Fix OutputStream::write_all()

Gir.toml, src/auto/application.rs
This patch depends on the one adding OptionArg and OptionFlags to glib-rs.
=> Command-line option support for gio::Application

src/input_stream.rs, src/output_stream.rs, tests/std_io_copy.rs
I added impls for Debug, PartialEq, Eq, Hash, Clone to the new helper structs.
@sdroege There already are `into_input_stream` and `into_output_stream` methods on the structs to turn them back into the gio types. Or did you mean something else?
=> Add impls for new std::io::{Read,Write} structs

src/socket.rs
It's unsafe as one could pass any possible number as fd/handle here from
safe code otherwise.
=> Mark functions to create a socket from raw fd/socket as unsafe

Cargo.toml, Gir.toml, src/lib.rs, src/subclass/application.rs, src/subclass/mod.rs
Based on code by Dirk Van Haerenborgh @vhdirk from https://github.com/gtk-rs/gobject-subclass
=> Add support for subclassing gio::Application

src/unix_input_stream.rs, src/unix_output_stream.rs
#208 broke apveyor doc test
https://ci.appveyor.com/project/GuillaumeGomez/gtk/builds/24553406/job/nq5dssq5o0dhxnj6#L209
```
--> C:\Users\appveyor\.cargo\git\checkouts\gio-a4b825b310a073b9\10df4f6\src\unix_input_stream.rs:10:14
|
10 | use std::os::unix::io::{RawFd, AsRawFd, IntoRawFd, FromRawFd};
|              ^^^^ could not find `unix` in `os`
```
cc @GuillaumeGomez, @sdroege
=> Fix generating docs for UnixXXXStream

src/lib.rs, src/read_input_stream.rs, src/subclass/input_stream.rs, src/subclass/io_stream.rs, src/subclass/mod.rs, src/subclass/output_stream.rs, src/subclass/seekable.rs, src/write_output_stream.rs
I'll also do the `Seekable` interface in a bit. Don't merge yet, but review :)
Also see https://github.com/gtk-rs/gio/issues/160
CC @brainblasted @GuillaumeGomez @EPashkin @fkrull
=> Add support for subclassing Input/OutputStream

Gir.toml
Part of https://github.com/gtk-rs/gtk/issues/892
I hope that CI will pass without updating submodules
cc @GuillaumeGomez, @sdroege
=> Remove ignoring not generated property

src/file.rs, src/file_enumerator.rs, src/input_stream.rs, src/output_stream.rs, src/pollable_input_stream.rs, src/pollable_output_stream.rs, src/socket.rs, src/socket_listener.rs, src/subprocess.rs
=> IsA<Cancellable> generic instead of concrete Option<&Cancellable>

src/io_stream.rs, src/lib.rs, src/pollable_output_stream.rs, src/prelude.rs
In many places a combination of both is required so let's make this a
bit simpler for users.
----
That's basically most of the boilerplate in the gio_async_tls.rs example. I'll update that once this one here is merged.
=> Add an AsyncRead+AsyncWrite adapter for IOStream

src/subclass/input_stream.rs, src/subclass/io_stream.rs, src/subclass/output_stream.rs, src/subclass/seekable.rs
It makes the intentions clearer and potentially results in simpler
assembly, at least in debug builds.
=> Use mem::ManuallyDrop instead of mem::forget() everywhere

src/cancellable.rs, src/lib.rs
This PR is meant to fail until we put back the old function pointer cast system. It'll be used to enforce that at least this cast will be correct.
cc @EPashkin @sdroege
=> Add callback check

Gir.toml, src/auto/application.rs, src/auto/application_command_line.rs, src/subclass/application.rs
In https://github.com/gtk-rs/glib/pull/634 we added glib::VariantDict so this PR turns on support for it.
This ought to fix #291 which is on the current release roadmap (https://github.com/gtk-rs/release/issues/115)
=> Support various things which needed glib::VariantDict

.travis.yml, build.rs, src/lib.rs, src/read_input_stream.rs, src/subclass/application.rs
With https://github.com/gtk-rs/lgpl-docs/pull/73 landed, this ought to bring `gio` to the point of clippy clean with CI to enforce that.
=> Clippy-clean plus CI

Cargo.toml, src/input_stream.rs, src/lib.rs, tests/futures.rs
@sdroege : finally found a solution by adding a `Transitioning` state. We should wait for me to implement `AsyncBufRead` before merging but I'd be interested about your feedback already, especially if you know of a better pattern to handle state changes.
=> input_stream: add AsyncBufRead adapter
